name = "mycompanyrtl"
compatibility_date = "2024-02-02"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

[build.environment]
NODE_VERSION = "18.18.0"
NPM_VERSION = "9.8.0"

[site]
bucket = ".vercel/output/static"